package com.tribex.groovebox.persistence

import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import java.io.IOException

@RunWith(AndroidJUnit4::class)
class MigrationTest {

    private val TEST_DB = "migration-test"

    @get:Rule
    val helper: MigrationTestHelper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        ProjectDatabase::class.java.canonicalName,
        FrameworkSQLiteOpenHelperFactory()
    )

    @Test
    @Throws(IOException::class)
    fun createAndValidateFirstVersion() {
        // Create the database with version 1
        val db = helper.createDatabase(TEST_DB, 1)
        
        // Insert some data using SQL (since we can't use DAO here easily)
        db.execSQL("INSERT INTO projects (id, name, bpm, createdAt, lastModified) VALUES ('proj1', 'Test Project', 120.0, 1000, 1000)")
        
        // Close the database
        db.close()
        
        // Re-open via helper to validate schema
        // This validates that the schema generated by Room matches the schema version 1
        helper.runMigrationsAndValidate(TEST_DB, 1, true)
    }
}
